working cf-watch script

diff --git a/@cf-watch b/@cf-watch
--- a/@cf-watch
+++ b/@cf-watch
@@ -2,6 +2,81 @@
 # Script to watch one or more CI pipelines in Codefresh. This makes it easy to
 # see when your pipelines have completed.
 
+# For tput codes (terminfo), see
+# https://gist.github.com/izabera/9903f9d942e2667ef2cb
+
+# Go to start of previous line
+UPLINE="$(tput cuu1)$(tput cr)"
+# Clear to end of line
+ERASERIGHT=$(tput el)
+
+# https://unix.stackexchange.com/questions/269077/tput-setaf-color-table-how-to-determine-color-codes
+COLOR_RED=$(tput setaf 1)
+COLOR_GREEN=$(tput setaf 2)
+COLOR_YELLOW=$(tput setaf 3)
+COLOR_BLUE=$(tput setaf 4)
+COLOR_MAGENTA=$(tput setaf 5)
+COLOR_CYAN=$(tput setaf 6)
+COLOR_WHITE=$(tput setaf 7)
+RESET_STYLE=$(tput sgr0)
+
+CURSOR_INVISIBLE=$(tput civis)
+CURSOR_RESET=$(tput cnorm)
+
+current_cursor_row=0
+
+print_status () {
+    status="$1"
+
+    # Reset cursor to the top and clear lines
+    while [[ "$current_cursor_row" -gt 0 ]]; do
+        printf "${UPLINE}"
+        current_cursor_row=$((current_cursor_row - 1))
+    done
+
+    while IFS= read -r s; do
+        state=$(echo $s | jq -r '.status')
+        trigger=$(echo $s | jq -r '.trigger')
+
+        printf "${ERASERIGHT}"
+
+        if [[ "$state" == "running" ]]; then
+            printf "${COLOR_BLUE}[Running]${RESET_STYLE} $trigger\n"
+        elif [[ "$state" == "success" ]]; then
+            printf "${COLOR_GREEN}[Done]${RESET_STYLE} $trigger\n"
+        elif [[ "$state" == "error" ]]; then
+            printf "${COLOR_RED}[Failed]${RESET_STYLE} $trigger\n"
+        elif [[ "$state" == "terminated" ]]; then
+            printf "${COLOR_MAGENTA}[Terminated]${RESET_STYLE} $trigger\n"
+        fi
+
+        current_cursor_row=$((current_cursor_row + 1))
+    done <<< "$status"
+}
+
+check_if_done() {
+    status="$1"
+
+    completed=0
+    total=0
+
+    while IFS= read -r s; do
+        state=$(echo $s | jq -r '.status')
+
+        if [[ "$state" != "running" ]]; then
+            completed=$((completed + 1))
+        fi
+
+        total=$((total + 1))
+    done <<< "$status"
+
+    if [[ $completed -eq $total ]]; then
+        exit 0
+    fi
+}
+
+
+# Script args
 PIPELINE_NAME="optimove-microservices/$1"
 REPO_NAME="$2"
 
@@ -10,50 +85,25 @@ if [[ -z "$PIPELINE_NAME" || -z "$REPO_NAME" ]]; then
     exit 1
 fi
 
+# Find running builds for given pipeline and repo
 BUILD_IDS=$(codefresh get builds --pipeline-name "$PIPELINE_NAME" --status running -o json \
-    | jq -r ".[] | select(.repository | contains(\"$REPO_NAME\")) | .id")
+    | jq -r "if type==\"array\" then .[] else . end | select(.repository | contains(\"$REPO_NAME\")) | .id")
 
 if [[ -z "$BUILD_IDS" ]]; then
     echo "No running builds found."
     exit 2
 fi
 
+# Don't show cursor in the output
+printf "$CURSOR_INVISIBLE"
+trap "printf $CURSOR_RESET" EXIT
+
 while true; do
-    ALL_STATUS=$(codefresh get builds $BUILD_IDS -o json \
+    status=$(codefresh get builds $BUILD_IDS -o json \
         | jq -r -c 'if type=="array" then .[] else . end | {trigger, status, totalTime}')
 
-    printf "\r\033[0K\033[0;32m[Running]\033[0m "
+    print_status "$status"
+    check_if_done "$status"
 
-    COMPLETED=()
-    FAILED=()
-    TERMINATED=()
-
-    while IFS= read -r s; do
-        state=$(echo $s | jq -r '.status')
-
-        if [[ "$state" == "running" ]]; then
-            trigger=$(echo $s | jq -r '.trigger')
-            printf "$trigger "
-        elif [[ "$state" == "success" ]]; then
-            COMPLETED+=("$trigger")
-        elif [[ "$state" == "error" ]]; then
-            FAILED+=("$trigger")
-        elif [[ "$state" == "terminated" ]]; then
-            TERMINATED+=("$trigger")
-        fi
-    done <<< "$ALL_STATUS"
-
-    for s in "${COMPLETED[@]}"; do
-        printf "\r\033[0K\033[0;34m[Done]\033[0m $s\n"
-    done
-
-    for s in "${FAILED[@]}"; do
-        printf "\r\033[0K\033[0;31m[Failed]\033[0m $s\n"
-    done
-
-    for s in "${TERMINATED[@]}"; do
-        printf "\r\033[0K\033[0;35m\r[Terminated]\033[0m $s\n"
-    done
-
-    sleep 5
+    sleep 10
 done
